# Site Info
title: ""
tagline: ""
description: ""
baseurl: ""
url: https://koeonyack.github.io/aiforall-dashboard/
logo: ""

# Site configurations
#gems:
#  - jekyll-paginate
#markdown: kramdown
#kramdown:
#  input: GFM
#excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
#paginate:
#paginate_path: ''
#permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Ko Eon-yak
  description: Ko Eon-yak
  contact:
    github:    https://github.com/KoEonYack
    email:    mailto:21300035@handong.edu

google_analytics: 'UA-163305315-1'